In [1]:
pip install tableone

Requirement already satisfied: tableone in c:\programdata\anaconda3\lib\site-packages (0.7.10)
Requirement already satisfied: statsmodels>=0.8.0 in c:\programdata\anaconda3\lib\site-packages (from tableone) (0.12.2)
Requirement already satisfied: scipy>=0.18.1 in c:\programdata\anaconda3\lib\site-packages (from tableone) (1.7.1)
Requirement already satisfied: tabulate>=0.8.2 in c:\programdata\anaconda3\lib\site-packages (from tableone) (0.8.9)
Requirement already satisfied: numpy>=1.12.1 in c:\programdata\anaconda3\lib\site-packages (from tableone) (1.20.3)
Requirement already satisfied: pandas>=0.22.0 in c:\programdata\anaconda3\lib\site-packages (from tableone) (1.3.4)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.22.0->tableone) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.22.0->tableone) (2021.3)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.22.0->tableone) (1.16.0)
Requirement already satisfied: patsy>=0.5 in c:\programdata\anaconda3\lib\site-packages (from statsmodels>=0.8.0->tableone) (0.5.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from tableone import TableOne

%matplotlib inline

In [227]:
listdf2: [df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20]

In [3]:
def readdata(y):
    
    x = pd.read_csv(y,sep='	')
    x= x[[(x['AGE2']> 3)] and (x['AGE2']<=13)]
    x.loc[x['MJEVER'] > 5, 'MJEVER'] = np.nan
    x.loc[x['MJYFU'] > 900, 'MJYFU'] = np.nan
    x.loc[x['HERYFU'] > 900, 'HERYFU'] = np.nan
    x.loc[x['MJMFU'] > 80, 'MJMFU'] = np.nan
    x.loc[x['HERYFU'] > 800, 'HERYFU'] = np.nan
    x.loc[x['HERMFU'] > 80, 'HERMFU'] = np.nan
    x.loc[x['COCEVER'] > 80, 'COCEVER'] = np.nan
    x.loc[x['HEREVER'] > 80, 'HEREVER'] = np.nan
    x.loc[x['METHAMEVR'] > 80, 'METHAMEVR'] = np.nan

    return x

In [20]:
df10 = readdata('NSDUH_2010_Tab.csv')

C:\Users\tn09t\AppData\Local\Temp/ipykernel_14544/3479575668.py:1: DtypeWarning: Columns (2575) have mixed types.Specify dtype option on import or set low_memory=False.
  df19 = readdata('NSDUH_2019_Tab.csv')

In [ ]:
df11 = readdata('NSDUH_2011_Tab.csv')

In [ ]:
df12 = readdata('NSDUH_2012_Tab.csv')

In [ ]:
df13 = readdata('NSDUH_2013_Tab.csv')

In [ ]:
df10 = readdata('NSDUH_2010_Tab.csv')

In [51]:
df18 = readdata('NSDUH_2018_Tab.csv')

C:\Users\tn09t\AppData\Local\Temp/ipykernel_24952/2758257887.py:1: DtypeWarning: Columns (2525) have mixed types.Specify dtype option on import or set low_memory=False.
  df18 = readdata('NSDUH_2018_Tab.csv')

In [26]:
df19= readdata('NSDUH_2019_Tab.csv')

C:\Users\tn09t\AppData\Local\Temp/ipykernel_24952/2035134017.py:1: DtypeWarning: Columns (2575) have mixed types.Specify dtype option on import or set low_memory=False.
  df19= readdata('NSDUH_2019_Tab.csv')

In [21]:
df19.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31530 entries, 3 to 56135
Columns: 2741 entries, QUESTID2 to VEREP
dtypes: float64(407), int64(2332), object(2)
memory usage: 659.6+ MB

In [ ]:
.apply(lambda x : x if x <5   else np.nan)

In [314]:
df19= df19[[(df19['AGE2']> 3)] and (df19['AGE2']<=13)]
df19

,QUESTID2,FILEDATE,CIGEVER,CIGOFRSM,CIGWILYR,CIGTRY,CIGYFU,CIGMFU,CIGREC,CIG30USE,...,POVERTY3,TOOLONG,TROUBUND,PDEN10,COUTYP4,MAIIN102,AIIND102,ANALWT_C,VESTR,VEREP
3,51015143,10/09/2020,2,99,99,991,9991,91,91,91,...,1.0,2,2,2,2,2,2,2419.558820,40031,1
4,31825143,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,2,2,2,2,575.225454,40010,2
6,65565143,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,1,1,2,2,2198.053566,40040,2
13,79876143,10/09/2020,1,99,99,9,9999,99,1,30,...,1.0,2,2,2,3,2,2,5456.383858,40039,1
15,58786143,10/09/2020,2,4,4,991,9991,91,91,91,...,3.0,1,2,2,2,2,2,1453.792383,40002,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56131,29424730,10/09/2020,1,99,99,17,9999,99,4,93,...,3.0,2,2,3,3,2,2,2292.155935,40043,2
56132,71744730,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,2,2,2,2,564.527589,40023,1
56133,38044730,10/09/2020,2,4,4,991,9991,91,91,91,...,3.0,2,2,1,1,2,2,2717.640610,40009,1
56134,43164730,10/09/2020,2,3,4,991,9991,91,91,91,...,2.0,2,2,1,1,2,2,1853.439383,40046,1
56135,92074730,10/09/2020,2,4,4,991,9991,91,91,91,...,2.0,2,2,1,1,2,2,842.165187,40028,1

In [311]:

def dfyouth(x):
    x= x[(x['AGE2'] > 3) & (x['AGE2'] <=13)]
    return x

In [4]:
dfyouth(df19)

NameError: name 'dfyouth' is not defined

In [307]:
df20.apply(dfyouth)

KeyError: 'AGE2'

In [264]:
listdf = [df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20]
for i in listdf:
    dfyouth(i)

In [259]:
dfyouth(df19)

,QUESTID2,FILEDATE,CIGEVER,CIGOFRSM,CIGWILYR,CIGTRY,CIGYFU,CIGMFU,CIGREC,CIG30USE,...,POVERTY3,TOOLONG,TROUBUND,PDEN10,COUTYP4,MAIIN102,AIIND102,ANALWT_C,VESTR,VEREP
3,51015143,10/09/2020,2,99,99,991,9991,91,91,91,...,1.0,2,2,2,2,2,2,2419.558820,40031,1
4,31825143,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,2,2,2,2,575.225454,40010,2
6,65565143,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,1,1,2,2,2198.053566,40040,2
13,79876143,10/09/2020,1,99,99,9,9999,99,1,30,...,1.0,2,2,2,3,2,2,5456.383858,40039,1
15,58786143,10/09/2020,2,4,4,991,9991,91,91,91,...,3.0,1,2,2,2,2,2,1453.792383,40002,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56131,29424730,10/09/2020,1,99,99,17,9999,99,4,93,...,3.0,2,2,3,3,2,2,2292.155935,40043,2
56132,71744730,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,2,2,2,2,564.527589,40023,1
56133,38044730,10/09/2020,2,4,4,991,9991,91,91,91,...,3.0,2,2,1,1,2,2,2717.640610,40009,1
56134,43164730,10/09/2020,2,3,4,991,9991,91,91,91,...,2.0,2,2,1,1,2,2,1853.439383,40046,1
56135,92074730,10/09/2020,2,4,4,991,9991,91,91,91,...,2.0,2,2,1,1,2,2,842.165187,40028,1

In [260]:
df19

,QUESTID2,FILEDATE,CIGEVER,CIGOFRSM,CIGWILYR,CIGTRY,CIGYFU,CIGMFU,CIGREC,CIG30USE,...,POVERTY3,TOOLONG,TROUBUND,PDEN10,COUTYP4,MAIIN102,AIIND102,ANALWT_C,VESTR,VEREP
0,43295143,10/09/2020,1,99,99,13,9999,99,4,93,...,3.0,2,2,2,2,2,2,6613.865847,40004,2
1,65095143,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,2,2,2,2,6321.580570,40003,1
2,49405143,10/09/2020,1,99,99,22,9999,99,4,93,...,3.0,2,2,2,2,2,2,5045.607492,40008,1
3,51015143,10/09/2020,2,99,99,991,9991,91,91,91,...,1.0,2,2,2,2,2,2,2419.558820,40031,1
4,31825143,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,2,2,2,2,575.225454,40010,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56131,29424730,10/09/2020,1,99,99,17,9999,99,4,93,...,3.0,2,2,3,3,2,2,2292.155935,40043,2
56132,71744730,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,2,2,2,2,564.527589,40023,1
56133,38044730,10/09/2020,2,4,4,991,9991,91,91,91,...,3.0,2,2,1,1,2,2,2717.640610,40009,1
56134,43164730,10/09/2020,2,3,4,991,9991,91,91,91,...,2.0,2,2,1,1,2,2,1853.439383,40046,1
56135,92074730,10/09/2020,2,4,4,991,9991,91,91,91,...,2.0,2,2,1,1,2,2,842.165187,40028,1

In [234]:
df19.describe

<bound method NDFrame.describe of        QUESTID2    FILEDATE  CIGEVER  CIGOFRSM  CIGWILYR  CIGTRY  CIGYFU  \
0      43295143  10/09/2020        1        99        99      13    9999
1      65095143  10/09/2020        2        99        99     991    9991
2      49405143  10/09/2020        1        99        99      22    9999
3      51015143  10/09/2020        2        99        99     991    9991
4      31825143  10/09/2020        2        99        99     991    9991
...         ...         ...      ...       ...       ...     ...     ...
56131  29424730  10/09/2020        1        99        99      17    9999
56132  71744730  10/09/2020        2        99        99     991    9991
56133  38044730  10/09/2020        2         4         4     991    9991
56134  43164730  10/09/2020        2         3         4     991    9991
56135  92074730  10/09/2020        2         4         4     991    9991

       CIGMFU  CIGREC  CIG30USE  ...  POVERTY3  TOOLONG  TROUBUND  PDEN10  \
0          99       4        93  ...       3.0        2         2       2
1          91      91        91  ...       3.0        2         2       2
2          99       4        93  ...       3.0        2         2       2
3          91      91        91  ...       1.0        2         2       2
4          91      91        91  ...       3.0        2         2       2
...       ...     ...       ...  ...       ...      ...       ...     ...
56131      99       4        93  ...       3.0        2         2       3
56132      91      91        91  ...       3.0        2         2       2
56133      91      91        91  ...       3.0        2         2       1
56134      91      91        91  ...       2.0        2         2       1
56135      91      91        91  ...       2.0        2         2       1

       COUTYP4  MAIIN102  AIIND102     ANALWT_C  VESTR  VEREP
0            2         2         2  6613.865847  40004      2
1            2         2         2  6321.580570  40003      1
2            2         2         2  5045.607492  40008      1
3            2         2         2  2419.558820  40031      1
4            2         2         2   575.225454  40010      2
...        ...       ...       ...          ...    ...    ...
56131        3         2         2  2292.155935  40043      2
56132        2         2         2   564.527589  40023      1
56133        1         2         2  2717.640610  40009      1
56134        1         2         2  1853.439383  40046      1
56135        1         2         2   842.165187  40028      1

[56136 rows x 2741 columns]>

In [83]:
df19[['MJEVER','YESCHFLT']]

       MJEVER  YESCHFLT
3           2        99
4           2        99
6           1        99
13          1        99
15          2         1
...       ...       ...
56131       1        99
56132       1        99
56133       2         2
56134       1         3
56135       2         2

[31530 rows x 2 columns]

In [84]:
df19['MJEVER']

3        2
4        2
6        1
13       1
15       2
        ..
56131    1
56132    1
56133    2
56134    1
56135    2
Name: MJEVER, Length: 31530, dtype: int64

In [42]:
df19['YESCHFLT'].dtypes

dtype('float64')

In [29]:
df19['YESCHFLT'].astype('str')

3        nan
4        nan
6        nan
13       nan
15       1.0
        ...
56131    nan
56132    nan
56133    2.0
56134    3.0
56135    2.0
Name: YESCHFLT, Length: 31530, dtype: object

In [122]:

df19['YESCHFLT']= df19['YESCHFLT'].astype('category')

In [19]:
def dataconverting(x):
    if x <5:
        x == x
    else: 
        x == np.nan
    return x

In [121]:

df19['YESCHFLT'] = df19['YESCHFLT'].apply(lambda x : x if x <5   else np.nan)

In [269]:

df19.loc[df19['MJEVER'] > 5, 'MJEVER'] = np.nan
df19.loc[df19['MJYFU'] > 900, 'MJYFU'] = np.nan
df19.loc[df19['HERYFU'] > 900, 'HERYFU'] = np.nan
df19.loc[df19['MJMFU'] > 80, 'MJMFU'] = np.nan
df19.loc[df19['HERYFU'] > 800, 'HERYFU'] = np.nan
df19.loc[df19['HERMFU'] > 80, 'HERMFU'] = np.nan
df19.loc[df19['COCEVER'] > 80, 'COCEVER'] = np.nan

df19.loc[df19['HEREVER'] > 80, 'HEREVER'] = np.nan

df19.loc[df19['METHAMEVR'] > 80, 'METHAMEVR'] = np.nan
df19['YESCHFLT'] = df19['YESCHFLT'].apply(lambda x : x if x <5   else np.nan)

In [90]:
df19.loc[df19['MJEVER'] > 5, 'MJYFU'] = np.nan

In [111]:
df19['YESCHFLT'] = df19['YESCHFLT'].apply(lambda x : x if x <5   else np.nan)

TypeError: '<' not supported between instances of 'str' and 'int'

In [129]:

df19['YESCHWRK'] = df19['YESCHWRK'].apply(lambda x : x if x <5   else np.nan)

In [133]:
df19['YESCHWRK'].astype('category')

c:\ProgramData\Anaconda3\lib\site-packages\pandas\io\formats\format.py:1429: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  for val, m in zip(values.ravel(), mask.ravel())

3        NaN
4        NaN
6        NaN
13       NaN
15       1.0
        ...
56131    NaN
56132    NaN
56133    2.0
56134    3.0
56135    1.0
Name: YESCHWRK, Length: 31530, dtype: category
Categories (4, float64): [1.0, 2.0, 3.0, 4.0]

In [139]:

df19['YESCHIMP'] = df19['YESCHIMP'].apply(lambda x : x if x <5   else np.nan)

In [140]:
df19['YESCHIMP'].astype('category')

c:\ProgramData\Anaconda3\lib\site-packages\pandas\io\formats\format.py:1429: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  for val, m in zip(values.ravel(), mask.ravel())

3        NaN
4        NaN
6        NaN
13       NaN
15       2.0
        ...
56131    NaN
56132    NaN
56133    2.0
56134    3.0
56135    2.0
Name: YESCHIMP, Length: 31530, dtype: category
Categories (4, float64): [1.0, 2.0, 3.0, 4.0]

In [141]:
df19['YESCHINT'] = df19['YESCHINT'].apply(lambda x : x if x <5   else np.nan)

In [297]:
df119 = df19.apply(dfyouth)

KeyError: 'AGE2'

In [142]:
df19['YESCHINT'].astype('category')

3        NaN
4        NaN
6        NaN
13       NaN
15       1.0
        ...
56131    NaN
56132    NaN
56133    2.0
56134    2.0
56135    2.0
Name: YESCHINT, Length: 31530, dtype: float64

In [ ]:

df19['YETCGJOB1'] = df19['YETCGJOB1'].apply(lambda x : x if x <5   else np.nan)

In [ ]:
df19['YESCHINT'].astype('category')

In [ ]:

df19['YELSTGRD1'] = df19['YELSTGRD1'].apply(lambda x : x if x <5   else np.nan)

In [ ]:
df19['YELSTGRD1'].astype('category')

In [13]:
datatest = df19

In [32]:
df19

,QUESTID2,FILEDATE,CIGEVER,CIGOFRSM,CIGWILYR,CIGTRY,CIGYFU,CIGMFU,CIGREC,CIG30USE,...,POVERTY3,TOOLONG,TROUBUND,PDEN10,COUTYP4,MAIIN102,AIIND102,ANALWT_C,VESTR,VEREP
3,51015143,10/09/2020,2,99,99,991,9991,91,91,91,...,1.0,2,2,2,2,2,2,2419.558820,40031,1
4,31825143,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,2,2,2,2,575.225454,40010,2
6,65565143,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,1,1,2,2,2198.053566,40040,2
13,79876143,10/09/2020,1,99,99,9,9999,99,1,30,...,1.0,2,2,2,3,2,2,5456.383858,40039,1
15,58786143,10/09/2020,2,4,4,991,9991,91,91,91,...,3.0,1,2,2,2,2,2,1453.792383,40002,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56131,29424730,10/09/2020,1,99,99,17,9999,99,4,93,...,3.0,2,2,3,3,2,2,2292.155935,40043,2
56132,71744730,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,2,2,2,2,564.527589,40023,1
56133,38044730,10/09/2020,2,4,4,991,9991,91,91,91,...,3.0,2,2,1,1,2,2,2717.640610,40009,1
56134,43164730,10/09/2020,2,3,4,991,9991,91,91,91,...,2.0,2,2,1,1,2,2,1853.439383,40046,1
56135,92074730,10/09/2020,2,4,4,991,9991,91,91,91,...,2.0,2,2,1,1,2,2,842.165187,40028,1

In [39]:
list1 = ['YESCHFLT',
'YESCHWRK',
'YESCHIMP', 
'YESCHINT' ,
'YETCGJOB',
'YELSTGRD',
'YEPCHKHW',
'YEPHLPHW',
'YEPCHORE',
'YEPLMTTV',
'YEPLMTSN',
'YEPPROUD',
'YEYARGUP',
'YEYFGTSW',
'YEYFGTGP', 
'YEYHGUN', 
'YEYSELL',
'YEYSTOLE',
'YEYATTAK',
'YEVIOPRV',
'YESCHACT',
'YECOMACT',
'YEFAIACT',
'YEOTHACT',
'DSTNRV30',
'DSTNRV30',
'DSTCHR30',
'DSTNGD30',
'IMPSOC',
'IMPSOCM',
'YODPREV']
def dataclean(x):
        for y in list1:
                x[y]= x[y].apply(lambda a : a if a <80 else np.nan)

In [42]:
dataclean(df19)

In [43]:
df19

,QUESTID2,FILEDATE,CIGEVER,CIGOFRSM,CIGWILYR,CIGTRY,CIGYFU,CIGMFU,CIGREC,CIG30USE,...,POVERTY3,TOOLONG,TROUBUND,PDEN10,COUTYP4,MAIIN102,AIIND102,ANALWT_C,VESTR,VEREP
3,51015143,10/09/2020,2,99,99,991,9991,91,91,91,...,1.0,2,2,2,2,2,2,2419.558820,40031,1
4,31825143,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,2,2,2,2,575.225454,40010,2
6,65565143,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,1,1,2,2,2198.053566,40040,2
13,79876143,10/09/2020,1,99,99,9,9999,99,1,30,...,1.0,2,2,2,3,2,2,5456.383858,40039,1
15,58786143,10/09/2020,2,4,4,991,9991,91,91,91,...,3.0,1,2,2,2,2,2,1453.792383,40002,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56131,29424730,10/09/2020,1,99,99,17,9999,99,4,93,...,3.0,2,2,3,3,2,2,2292.155935,40043,2
56132,71744730,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,2,2,2,2,564.527589,40023,1
56133,38044730,10/09/2020,2,4,4,991,9991,91,91,91,...,3.0,2,2,1,1,2,2,2717.640610,40009,1
56134,43164730,10/09/2020,2,3,4,991,9991,91,91,91,...,2.0,2,2,1,1,2,2,1853.439383,40046,1
56135,92074730,10/09/2020,2,4,4,991,9991,91,91,91,...,2.0,2,2,1,1,2,2,842.165187,40028,1

In [44]:
df19[['YESCHFLT',
'YESCHWRK',
'YESCHIMP', 
'YESCHINT' ,
'YETCGJOB',
'YELSTGRD',
'YEPCHKHW',
'YEPHLPHW',
'YEPCHORE',
'YEPLMTTV',
'YEPLMTSN',
'YEPPROUD',
'YEYARGUP',
'YEYFGTSW',
'YEYFGTGP', 
'YEYHGUN', 
'YEYSELL',
'YEYSTOLE',
'YEYATTAK',
'YEVIOPRV',
'YESCHACT',
'YECOMACT',
'YEFAIACT',
'YEOTHACT',
'DSTNRV30',
'DSTNRV30',
'DSTCHR30',
'DSTNGD30',
'IMPSOC',
'IMPSOCM',
'YODPREV']]

,YESCHFLT,YESCHWRK,YESCHIMP,YESCHINT,YETCGJOB,YELSTGRD,YEPCHKHW,YEPHLPHW,YEPCHORE,YEPLMTTV,...,YECOMACT,YEFAIACT,YEOTHACT,DSTNRV30,DSTNRV30,DSTCHR30,DSTNGD30,IMPSOC,IMPSOCM,YODPREV
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.0,3.0,4.0,5.0,1.0,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,2.0,4.0,3.0,2.0,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.0,4.0,5.0,5.0,1.0,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.0,4.0,3.0,3.0,3.0,NaN,NaN
15,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,4.0,4.0,...,3.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.0,4.0,4.0,4.0,1.0,NaN,NaN
56132,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.0,3.0,5.0,5.0,2.0,NaN,NaN
56133,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,4.0,...,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0
56134,3.0,3.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,...,2.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
56135,2.0,1.0,2.0,2.0,1.0,2.0,2.0,3.0,2.0,1.0,...,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0

In [272]:
def datatype(x):
    for a in list1:                
                x[a] = x[a].astype('category')

In [56]:
df19[['YESCHFLT',
'YESCHWRK',
'YESCHIMP', 
'YESCHINT' ,
'YETCGJOB',
'YELSTGRD',
'YEPCHKHW',
'YEPHLPHW',
'YEPCHORE',
'YEPLMTTV',
'YEPLMTSN',
'YEPPROUD',
'YEYARGUP',
'YEYFGTSW',
'YEYFGTGP', 
'YEYHGUN', 
'YEYSELL',
'YEYSTOLE',
'YEYATTAK',
'YEVIOPRV',
'YESCHACT',
'YECOMACT',
'YEFAIACT',
'YEOTHACT',
'DSTNRV30',
'DSTNRV30',
'DSTCHR30',
'DSTNGD30',
'IMPSOC',
'IMPSOCM',
'YODPREV']].apply(lambda x: x.astype('category'))

KeyError: "None of [Index(['YESCHFLT', 'YESCHWRK', 'YESCHIMP', 'YESCHINT', 'YETCGJOB', 'YELSTGRD',\n       'YEPCHKHW', 'YEPHLPHW', 'YEPCHORE', 'YEPLMTTV', 'YEPLMTSN', 'YEPPROUD',\n       'YEYARGUP', 'YEYFGTSW', 'YEYFGTGP', 'YEYHGUN', 'YEYSELL', 'YEYSTOLE',\n       'YEYATTAK', 'YEVIOPRV', 'YESCHACT', 'YECOMACT', 'YEFAIACT', 'YEOTHACT',\n       'DSTNRV30', 'DSTNRV30', 'DSTCHR30', 'DSTNGD30', 'IMPSOC', 'IMPSOCM',\n       'YODPREV'],\n      dtype='object')] are in the [index]"

In [45]:
df19[['YESCHFLT','YESCHWRK','YESCHIMP', 'YESCHINT' ,'YETCGJOB','YELSTGRD','YEPCHKHW','YEPHLPHW','YEPCHORE','YEPLMTTV','YEPLMTSN','YEPPROUD','YEYARGUP','YEYFGTSW','YEYFGTGP', 'YEYHGUN', 'YEYSELL','YEYSTOLE','YEYATTAK','YEVIOPRV',
'YESCHACT','YECOMACT','YEFAIACT','YEOTHACT','DSTNRV30','DSTNRV30','DSTCHR30','DSTNGD30','IMPSOC','IMPSOCM','YODPREV']].dtypes

YESCHFLT    float64
YESCHWRK    float64
YESCHIMP    float64
YESCHINT    float64
YETCGJOB    float64
YELSTGRD    float64
YEPCHKHW    float64
YEPHLPHW    float64
YEPCHORE    float64
YEPLMTTV    float64
YEPLMTSN    float64
YEPPROUD    float64
YEYARGUP    float64
YEYFGTSW    float64
YEYFGTGP    float64
YEYHGUN     float64
YEYSELL     float64
YEYSTOLE    float64
YEYATTAK    float64
YEVIOPRV    float64
YESCHACT    float64
YECOMACT    float64
YEFAIACT    float64
YEOTHACT    float64
DSTNRV30    float64
DSTNRV30    float64
DSTCHR30    float64
DSTNGD30    float64
IMPSOC      float64
IMPSOCM     float64
YODPREV     float64
dtype: object

In [46]:
df19.astype('category')

,QUESTID2,FILEDATE,CIGEVER,CIGOFRSM,CIGWILYR,CIGTRY,CIGYFU,CIGMFU,CIGREC,CIG30USE,...,POVERTY3,TOOLONG,TROUBUND,PDEN10,COUTYP4,MAIIN102,AIIND102,ANALWT_C,VESTR,VEREP
3,51015143,10/09/2020,2,99,99,991,9991,91,91,91,...,1.0,2,2,2,2,2,2,2419.558820,40031,1
4,31825143,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,2,2,2,2,575.225454,40010,2
6,65565143,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,1,1,2,2,2198.053566,40040,2
13,79876143,10/09/2020,1,99,99,9,9999,99,1,30,...,1.0,2,2,2,3,2,2,5456.383858,40039,1
15,58786143,10/09/2020,2,4,4,991,9991,91,91,91,...,3.0,1,2,2,2,2,2,1453.792383,40002,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56131,29424730,10/09/2020,1,99,99,17,9999,99,4,93,...,3.0,2,2,3,3,2,2,2292.155935,40043,2
56132,71744730,10/09/2020,2,99,99,991,9991,91,91,91,...,3.0,2,2,2,2,2,2,564.527589,40023,1
56133,38044730,10/09/2020,2,4,4,991,9991,91,91,91,...,3.0,2,2,1,1,2,2,2717.640610,40009,1
56134,43164730,10/09/2020,2,3,4,991,9991,91,91,91,...,2.0,2,2,1,1,2,2,1853.439383,40046,1
56135,92074730,10/09/2020,2,4,4,991,9991,91,91,91,...,2.0,2,2,1,1,2,2,842.165187,40028,1

In [47]:
df19.dtypes

QUESTID2      int64
FILEDATE     object
CIGEVER       int64
CIGOFRSM      int64
CIGWILYR      int64
             ...
MAIIN102      int64
AIIND102      int64
ANALWT_C    float64
VESTR         int64
VEREP         int64
Length: 2741, dtype: object

In [273]:
dataclean(df19)

In [274]:
datatype(df19)

In [110]:
df19['YESCHFLT'] = df19['YESCHFLT'].astype('str')

In [48]:
columns = ['MJEVER','COCEVER','METHAMFLAG','HEREVER','METHAMEVR','YESCHFLT','YESCHWRK','YESCHIMP', 'YESCHINT' ,'YETCGJOB','YELSTGRD','YEPCHKHW','YEPHLPHW','YEPCHORE','YEPLMTTV','YEPLMTSN','YEPPROUD','YEYARGUP','YEYFGTSW','YEYFGTGP', 'YEYHGUN', 'YEYSELL','YEYSTOLE','YEYATTAK','YEVIOPRV',
'YESCHACT','YECOMACT','YEFAIACT','YEOTHACT','DSTNRV30','DSTCHR30','DSTNGD30','IMPSOC','IMPSOCM','YODPREV']
categorical = ['MJEVER','COCEVER','METHAMFLAG','HEREVER','METHAMEVR','YESCHFLT','YESCHWRK','YESCHIMP', 'YESCHINT' ,'YETCGJOB','YELSTGRD','YEPCHKHW','YEPHLPHW','YEPCHORE','YEPLMTTV','YEPLMTSN','YEPPROUD','YEYARGUP','YEYFGTSW','YEYFGTGP', 'YEYHGUN', 'YEYSELL','YEYSTOLE','YEYATTAK','YEVIOPRV',
'YESCHACT','YECOMACT','YEFAIACT','YEOTHACT','DSTNRV30','DSTCHR30','DSTNGD30','IMPSOC','IMPSOCM','YODPREV']
groupby = 'MJEVER'#Total_Drinkday,
nonnormal = []

In [49]:

mytable19 = TableOne(df19, columns=columns ,categorical = categorical,missing= True, groupby=groupby)

c:\ProgramData\Anaconda3\lib\site-packages\tableone\tableone.py:991: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  df['percent'] = df['freq'].div(df.freq.sum(level=0),

In [284]:
mytable20 = TableOne(dataclean(dfyouth(df20)), columns=columns ,categorical = categorical,missing= True, groupby=groupby)

C:\Users\tn09t\AppData\Local\Temp/ipykernel_20756/364456033.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[y]= x[y].apply(lambda a : a if a <80 else np.nan)

AttributeError: 'NoneType' object has no attribute 'empty'

In [56]:

print(mytable19.tabulate(tablefmt="fancy_grid"))

╒═══════════════════╤═════╤═══════════╤══════════════╤═══════════════╤═══════════════╕
│                   │     │ Missing   │ Overall      │ 1.0           │ 2.0           │
╞═══════════════════╪═════╪═══════════╪══════════════╪═══════════════╪═══════════════╡
│ n                 │     │           │ 31530        │ 12216         │ 19289         │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ MJEVER, n (%)     │ 1.0 │ 25        │ 12216 (38.8) │ 12216 (100.0) │               │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 19289 (61.2) │               │ 19289 (100.0) │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ COCEVER, n (%)    │ 1.0 │ 10        │ 2366 (7.5)   │ 2322 (19.0)   │ 44 (0.2)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 29154 (92.5) │ 9891 (81.0)   │ 19240 (99.8)  │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ METHAMFLAG, n (%) │ 0   │ 0         │ 30857 (97.9) │ 11564 (94.7)  │ 19268 (99.9)  │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 1   │           │ 673 (2.1)    │ 652 (5.3)     │ 21 (0.1)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ HEREVER, n (%)    │ 1.0 │ 27        │ 305 (1.0)    │ 301 (2.5)     │ 4 (0.0)       │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 31198 (99.0) │ 11915 (97.5)  │ 19262 (100.0) │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ METHAMEVR, n (%)  │ 1.0 │ 51        │ 673 (2.1)    │ 652 (5.3)     │ 21 (0.1)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 30806 (97.9) │ 11561 (94.7)  │ 19224 (99.9)  │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YESCHFLT, n (%)   │ 1.0 │ 18847     │ 3053 (24.1)  │ 376 (17.0)    │ 2673 (25.6)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 6404 (50.5)  │ 1009 (45.6)   │ 5385 (51.5)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 2354 (18.6)  │ 551 (24.9)    │ 1801 (17.2)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 872 (6.9)    │ 278 (12.6)    │ 594 (5.7)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YESCHWRK, n (%)   │ 1.0 │ 18870     │ 2804 (22.1)  │ 334 (15.1)    │ 2465 (23.6)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 6265 (49.5)  │ 967 (43.7)    │ 5291 (50.7)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 2632 (20.8)  │ 616 (27.8)    │ 2014 (19.3)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 959 (7.6)    │ 298 (13.5)    │ 660 (6.3)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YESCHIMP, n (%)   │ 1.0 │ 18869     │ 3866 (30.5)  │ 413 (18.7)    │ 3444 (33.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 5595 (44.2)  │ 945 (42.7)    │ 4648 (44.6)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 2330 (18.4)  │ 585 (26.4)    │ 1744 (16.7)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 870 (6.9)    │ 270 (12.2)    │ 597 (5.7)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YESCHINT, n (%)   │ 1.0 │ 18865     │ 2672 (21.1)  │ 287 (13.0)    │ 2382 (22.8)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 6299 (49.7)  │ 1004 (45.4)   │ 5289 (50.7)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 2594 (20.5)  │ 584 (26.4)    │ 2006 (19.2)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 1100 (8.7)   │ 338 (15.3)    │ 760 (7.3)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YETCGJOB, n (%)   │ 1.0 │ 18863     │ 3817 (30.1)  │ 542 (24.5)    │ 3271 (31.3)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 5642 (44.5)  │ 925 (41.8)    │ 4710 (45.1)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 2272 (17.9)  │ 474 (21.4)    │ 1795 (17.2)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 936 (7.4)    │ 272 (12.3)    │ 662 (6.3)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YELSTGRD, n (%)   │ 1.0 │ 19111     │ 4505 (36.3)  │ 467 (21.4)    │ 4034 (39.4)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 4825 (38.9)  │ 892 (40.9)    │ 3930 (38.4)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 1935 (15.6)  │ 556 (25.5)    │ 1374 (13.4)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 585 (4.7)    │ 210 (9.6)     │ 375 (3.7)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 5.0 │           │ 569 (4.6)    │ 55 (2.5)      │ 513 (5.0)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEPCHKHW, n (%)   │ 1.0 │ 18899     │ 6558 (51.9)  │ 807 (36.6)    │ 5742 (55.1)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 3647 (28.9)  │ 694 (31.5)    │ 2949 (28.3)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 1350 (10.7)  │ 351 (15.9)    │ 996 (9.6)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 1076 (8.5)   │ 351 (15.9)    │ 725 (7.0)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEPHLPHW, n (%)   │ 1.0 │ 18907     │ 7154 (56.7)  │ 922 (41.9)    │ 6227 (59.8)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 2823 (22.4)  │ 499 (22.7)    │ 2317 (22.3)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 1292 (10.2)  │ 329 (14.9)    │ 962 (9.2)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 1354 (10.7)  │ 451 (20.5)    │ 900 (8.6)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEPCHORE, n (%)   │ 1.0 │ 18278     │ 6797 (51.3)  │ 1208 (52.6)   │ 5582 (51.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 5081 (38.3)  │ 799 (34.8)    │ 4278 (39.1)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 954 (7.2)    │ 184 (8.0)     │ 766 (7.0)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 420 (3.2)    │ 104 (4.5)     │ 315 (2.9)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEPLMTTV, n (%)   │ 1.0 │ 18324     │ 1815 (13.7)  │ 187 (8.2)     │ 1625 (14.9)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 3711 (28.1)  │ 444 (19.4)    │ 3263 (29.9)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 2487 (18.8)  │ 398 (17.4)    │ 2086 (19.1)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 5193 (39.3)  │ 1264 (55.1)   │ 3925 (36.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEPLMTSN, n (%)   │ 1.0 │ 19139     │ 4661 (37.6)  │ 686 (31.2)    │ 3971 (39.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 3430 (27.7)  │ 683 (31.0)    │ 2744 (27.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 1920 (15.5)  │ 433 (19.7)    │ 1483 (14.6)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 2380 (19.2)  │ 400 (18.2)    │ 1977 (19.4)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEPPROUD, n (%)   │ 1.0 │ 18279     │ 7375 (55.7)  │ 996 (43.3)    │ 6373 (58.3)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 3899 (29.4)  │ 742 (32.3)    │ 3152 (28.8)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 1331 (10.0)  │ 359 (15.6)    │ 970 (8.9)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 646 (4.9)    │ 201 (8.7)     │ 443 (4.1)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEYARGUP, n (%)   │ 1.0 │ 18436     │ 2712 (20.7)  │ 257 (11.2)    │ 2451 (22.7)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 3854 (29.4)  │ 538 (23.5)    │ 3314 (30.7)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 2784 (21.3)  │ 565 (24.7)    │ 2217 (20.5)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 1318 (10.1)  │ 284 (12.4)    │ 1030 (9.5)    │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 5.0 │           │ 2426 (18.5)  │ 642 (28.1)    │ 1781 (16.5)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEYFGTSW, n (%)   │ 1.0 │ 18270     │ 10891 (82.1) │ 1635 (71.2)   │ 9243 (84.4)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 1820 (13.7)  │ 454 (19.8)    │ 1365 (12.5)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 382 (2.9)    │ 139 (6.1)     │ 241 (2.2)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 91 (0.7)     │ 40 (1.7)      │ 51 (0.5)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 5.0 │           │ 76 (0.6)     │ 27 (1.2)      │ 49 (0.4)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEYFGTGP, n (%)   │ 1.0 │ 18285     │ 11702 (88.4) │ 1835 (80.0)   │ 9857 (90.1)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 1224 (9.2)   │ 343 (15.0)    │ 876 (8.0)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 208 (1.6)    │ 71 (3.1)      │ 137 (1.3)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 64 (0.5)     │ 25 (1.1)      │ 39 (0.4)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 5.0 │           │ 47 (0.4)     │ 19 (0.8)      │ 28 (0.3)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEYHGUN, n (%)    │ 1.0 │ 18267     │ 12594 (95.0) │ 2066 (89.9)   │ 10512 (96.0)  │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 437 (3.3)    │ 135 (5.9)     │ 302 (2.8)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 105 (0.8)    │ 42 (1.8)      │ 63 (0.6)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 53 (0.4)     │ 25 (1.1)      │ 28 (0.3)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 5.0 │           │ 74 (0.6)     │ 30 (1.3)      │ 44 (0.4)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEYSELL, n (%)    │ 1.0 │ 18233     │ 13008 (97.8) │ 2048 (89.2)   │ 10944 (99.6)  │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 145 (1.1)    │ 120 (5.2)     │ 25 (0.2)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 54 (0.4)     │ 46 (2.0)      │ 8 (0.1)       │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 38 (0.3)     │ 33 (1.4)      │ 5 (0.0)       │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 5.0 │           │ 52 (0.4)     │ 49 (2.1)      │ 3 (0.0)       │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEYSTOLE, n (%)   │ 1.0 │ 18237     │ 12898 (97.0) │ 2069 (90.0)   │ 10813 (98.5)  │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 263 (2.0)    │ 134 (5.8)     │ 129 (1.2)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 68 (0.5)     │ 47 (2.0)      │ 21 (0.2)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 30 (0.2)     │ 20 (0.9)      │ 10 (0.1)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 5.0 │           │ 34 (0.3)     │ 28 (1.2)      │ 6 (0.1)       │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEYATTAK, n (%)   │ 1.0 │ 18248     │ 12655 (95.3) │ 2073 (90.2)   │ 10567 (96.4)  │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 513 (3.9)    │ 177 (7.7)     │ 335 (3.1)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 68 (0.5)     │ 26 (1.1)      │ 42 (0.4)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 21 (0.2)     │ 10 (0.4)      │ 11 (0.1)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 5.0 │           │ 25 (0.2)     │ 13 (0.6)      │ 12 (0.1)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEVIOPRV, n (%)   │ 1.0 │ 18363     │ 1622 (12.3)  │ 255 (11.1)    │ 1361 (12.5)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 11545 (87.7) │ 2036 (88.9)   │ 9499 (87.5)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YESCHACT, n (%)   │ 0.0 │ 18296     │ 2329 (17.6)  │ 495 (21.6)    │ 1831 (16.8)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 1.0 │           │ 3407 (25.7)  │ 618 (27.0)    │ 2783 (25.5)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 3498 (26.4)  │ 618 (27.0)    │ 2878 (26.3)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 4000 (30.2)  │ 558 (24.4)    │ 3438 (31.5)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YECOMACT, n (%)   │ 0.0 │ 18367     │ 3421 (26.0)  │ 700 (30.6)    │ 2718 (25.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 1.0 │           │ 3481 (26.4)  │ 592 (25.9)    │ 2883 (26.5)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 2829 (21.5)  │ 520 (22.8)    │ 2305 (21.2)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 3432 (26.1)  │ 473 (20.7)    │ 2958 (27.2)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEFAIACT, n (%)   │ 0.0 │ 18415     │ 5814 (44.3)  │ 1205 (52.9)   │ 4604 (42.5)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 1.0 │           │ 2800 (21.3)  │ 482 (21.2)    │ 2316 (21.4)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 1683 (12.8)  │ 282 (12.4)    │ 1398 (12.9)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 2818 (21.5)  │ 309 (13.6)    │ 2504 (23.1)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEOTHACT, n (%)   │ 0.0 │ 18340     │ 8342 (63.2)  │ 1582 (69.1)   │ 6750 (62.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 1.0 │           │ 2614 (19.8)  │ 393 (17.2)    │ 2217 (20.4)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 1048 (7.9)   │ 196 (8.6)     │ 851 (7.8)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 1186 (9.0)   │ 118 (5.2)     │ 1068 (9.8)    │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤

In [53]:
dataclean(df18)

In [54]:
mytable18 = TableOne(df18, columns=columns ,categorical = categorical,missing= True, groupby=groupby)

c:\ProgramData\Anaconda3\lib\site-packages\tableone\tableone.py:991: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  df['percent'] = df['freq'].div(df.freq.sum(level=0),

In [55]:
print(mytable18.tabulate(tablefmt="fancy_grid"))

╒═══════════════════╤═════╤═══════════╤══════════════╤═══════════════╤═══════════════╕
│                   │     │ Missing   │ Overall      │ 1.0           │ 2.0           │
╞═══════════════════╪═════╪═══════════╪══════════════╪═══════════════╪═══════════════╡
│ n                 │     │           │ 30792        │ 11493         │ 19268         │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ MJEVER, n (%)     │ 1.0 │ 31        │ 11493 (37.4) │ 11493 (100.0) │               │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 19268 (62.6) │               │ 19268 (100.0) │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ COCEVER, n (%)    │ 1.0 │ 15        │ 2300 (7.5)   │ 2264 (19.7)   │ 35 (0.2)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 28477 (92.5) │ 9227 (80.3)   │ 19225 (99.8)  │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ METHAMFLAG, n (%) │ 0   │ 0         │ 30137 (97.9) │ 10864 (94.5)  │ 19244 (99.9)  │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 1   │           │ 655 (2.1)    │ 629 (5.5)     │ 24 (0.1)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ HEREVER, n (%)    │ 1.0 │ 25        │ 354 (1.2)    │ 343 (3.0)     │ 10 (0.1)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 30413 (98.8) │ 11150 (97.0)  │ 19237 (99.9)  │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ METHAMEVR, n (%)  │ 1.0 │ 49        │ 655 (2.1)    │ 629 (5.5)     │ 24 (0.1)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 30088 (97.9) │ 10859 (94.5)  │ 19204 (99.9)  │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YESCHFLT, n (%)   │ 1.0 │ 18231     │ 3224 (25.7)  │ 374 (18.3)    │ 2845 (27.1)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 6410 (51.0)  │ 943 (46.1)    │ 5461 (52.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 2156 (17.2)  │ 491 (24.0)    │ 1663 (15.8)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 771 (6.1)    │ 237 (11.6)    │ 534 (5.1)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YESCHWRK, n (%)   │ 1.0 │ 18241     │ 2956 (23.6)  │ 293 (14.3)    │ 2656 (25.3)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 6286 (50.1)  │ 942 (46.1)    │ 5339 (50.9)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 2494 (19.9)  │ 585 (28.6)    │ 1909 (18.2)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 815 (6.5)    │ 225 (11.0)    │ 589 (5.6)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YESCHIMP, n (%)   │ 1.0 │ 18237     │ 4177 (33.3)  │ 411 (20.1)    │ 3759 (35.8)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 5565 (44.3)  │ 924 (45.2)    │ 4638 (44.2)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 2097 (16.7)  │ 500 (24.5)    │ 1596 (15.2)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 716 (5.7)    │ 209 (10.2)    │ 505 (4.8)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YESCHINT, n (%)   │ 1.0 │ 18240     │ 2800 (22.3)  │ 282 (13.8)    │ 2513 (23.9)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 6330 (50.4)  │ 976 (47.8)    │ 5348 (51.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 2450 (19.5)  │ 523 (25.6)    │ 1925 (18.3)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 972 (7.7)    │ 262 (12.8)    │ 710 (6.8)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YETCGJOB, n (%)   │ 1.0 │ 18251     │ 3791 (30.2)  │ 478 (23.4)    │ 3310 (31.6)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 5660 (45.1)  │ 889 (43.5)    │ 4763 (45.4)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 2211 (17.6)  │ 446 (21.8)    │ 1765 (16.8)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 879 (7.0)    │ 230 (11.3)    │ 648 (6.2)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YELSTGRD, n (%)   │ 1.0 │ 18461     │ 4544 (36.9)  │ 481 (23.8)    │ 4061 (39.4)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 4836 (39.2)  │ 864 (42.7)    │ 3968 (38.5)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 1903 (15.4)  │ 465 (23.0)    │ 1437 (14.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 509 (4.1)    │ 170 (8.4)     │ 337 (3.3)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 5.0 │           │ 539 (4.4)    │ 43 (2.1)      │ 493 (4.8)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEPCHKHW, n (%)   │ 1.0 │ 18270     │ 6473 (51.7)  │ 684 (33.6)    │ 5783 (55.2)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 3659 (29.2)  │ 711 (34.9)    │ 2945 (28.1)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 1401 (11.2)  │ 349 (17.1)    │ 1050 (10.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 989 (7.9)    │ 292 (14.3)    │ 695 (6.6)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEPHLPHW, n (%)   │ 1.0 │ 18296     │ 7127 (57.0)  │ 839 (41.3)    │ 6281 (60.1)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 2715 (21.7)  │ 474 (23.3)    │ 2239 (21.4)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 1294 (10.4)  │ 303 (14.9)    │ 990 (9.5)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 1360 (10.9)  │ 416 (20.5)    │ 941 (9.0)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEPCHORE, n (%)   │ 1.0 │ 17635     │ 6653 (50.6)  │ 1108 (52.2)   │ 5541 (50.3)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 5065 (38.5)  │ 731 (34.4)    │ 4325 (39.2)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 978 (7.4)    │ 184 (8.7)     │ 793 (7.2)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 461 (3.5)    │ 99 (4.7)      │ 361 (3.3)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEPLMTTV, n (%)   │ 1.0 │ 17690     │ 1690 (12.9)  │ 174 (8.2)     │ 1512 (13.8)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 3598 (27.5)  │ 372 (17.6)    │ 3224 (29.4)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 2488 (19.0)  │ 370 (17.5)    │ 2115 (19.3)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 5326 (40.7)  │ 1200 (56.7)   │ 4120 (37.6)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEPLMTSN, n (%)   │ 1.0 │ 18468     │ 4631 (37.6)  │ 639 (31.4)    │ 3986 (38.8)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 3422 (27.8)  │ 652 (32.0)    │ 2770 (27.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 1959 (15.9)  │ 390 (19.2)    │ 1567 (15.2)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 2312 (18.8)  │ 355 (17.4)    │ 1953 (19.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEPPROUD, n (%)   │ 1.0 │ 17631     │ 7422 (56.4)  │ 903 (42.6)    │ 6513 (59.1)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 3818 (29.0)  │ 663 (31.3)    │ 3149 (28.6)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 1357 (10.3)  │ 371 (17.5)    │ 984 (8.9)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 564 (4.3)    │ 184 (8.7)     │ 379 (3.4)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEYARGUP, n (%)   │ 1.0 │ 17777     │ 2652 (20.4)  │ 245 (11.6)    │ 2399 (22.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 3831 (29.4)  │ 497 (23.5)    │ 3332 (30.6)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 2788 (21.4)  │ 497 (23.5)    │ 2290 (21.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 1311 (10.1)  │ 285 (13.5)    │ 1024 (9.4)    │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 5.0 │           │ 2433 (18.7)  │ 590 (27.9)    │ 1841 (16.9)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEYFGTSW, n (%)   │ 1.0 │ 17644     │ 10910 (83.0) │ 1570 (74.1)   │ 9328 (84.7)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 1736 (13.2)  │ 398 (18.8)    │ 1337 (12.1)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 328 (2.5)    │ 91 (4.3)      │ 235 (2.1)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 85 (0.6)     │ 29 (1.4)      │ 56 (0.5)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 5.0 │           │ 89 (0.7)     │ 31 (1.5)      │ 58 (0.5)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEYFGTGP, n (%)   │ 1.0 │ 17648     │ 11592 (88.2) │ 1695 (80.1)   │ 9885 (89.7)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 1230 (9.4)   │ 312 (14.8)    │ 916 (8.3)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 212 (1.6)    │ 69 (3.3)      │ 142 (1.3)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 50 (0.4)     │ 20 (0.9)      │ 30 (0.3)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 5.0 │           │ 60 (0.5)     │ 19 (0.9)      │ 41 (0.4)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEYHGUN, n (%)    │ 1.0 │ 17629     │ 12505 (95.0) │ 1926 (91.0)   │ 10565 (95.8)  │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 426 (3.2)    │ 115 (5.4)     │ 311 (2.8)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 109 (0.8)    │ 31 (1.5)      │ 78 (0.7)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 51 (0.4)     │ 20 (0.9)      │ 31 (0.3)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 5.0 │           │ 72 (0.5)     │ 24 (1.1)      │ 48 (0.4)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEYSELL, n (%)    │ 1.0 │ 17607     │ 12893 (97.8) │ 1875 (88.6)   │ 11005 (99.6)  │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 156 (1.2)    │ 124 (5.9)     │ 31 (0.3)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 53 (0.4)     │ 44 (2.1)      │ 9 (0.1)       │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 29 (0.2)     │ 23 (1.1)      │ 6 (0.1)       │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 5.0 │           │ 54 (0.4)     │ 51 (2.4)      │ 3 (0.0)       │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEYSTOLE, n (%)   │ 1.0 │ 17608     │ 12799 (97.1) │ 1919 (90.7)   │ 10868 (98.3)  │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 264 (2.0)    │ 120 (5.7)     │ 143 (1.3)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 63 (0.5)     │ 38 (1.8)      │ 25 (0.2)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 24 (0.2)     │ 18 (0.9)      │ 6 (0.1)       │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 5.0 │           │ 34 (0.3)     │ 21 (1.0)      │ 11 (0.1)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEYATTAK, n (%)   │ 1.0 │ 17607     │ 12579 (95.4) │ 1925 (90.8)   │ 10642 (96.3)  │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 509 (3.9)    │ 160 (7.5)     │ 348 (3.1)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 62 (0.5)     │ 22 (1.0)      │ 38 (0.3)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 4.0 │           │ 13 (0.1)     │ 5 (0.2)       │ 8 (0.1)       │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 5.0 │           │ 22 (0.2)     │ 9 (0.4)       │ 13 (0.1)      │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEVIOPRV, n (%)   │ 1.0 │ 17724     │ 1579 (12.1)  │ 209 (9.9)     │ 1366 (12.5)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 11489 (87.9) │ 1906 (90.1)   │ 9573 (87.5)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YESCHACT, n (%)   │ 0.0 │ 17662     │ 2179 (16.6)  │ 416 (19.7)    │ 1762 (16.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 1.0 │           │ 3363 (25.6)  │ 551 (26.1)    │ 2808 (25.5)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 3512 (26.7)  │ 608 (28.7)    │ 2897 (26.3)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 4076 (31.0)  │ 540 (25.5)    │ 3534 (32.1)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YECOMACT, n (%)   │ 0.0 │ 17742     │ 3217 (24.7)  │ 542 (25.7)    │ 2672 (24.4)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 1.0 │           │ 3417 (26.2)  │ 560 (26.6)    │ 2849 (26.1)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 2907 (22.3)  │ 498 (23.7)    │ 2406 (22.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 3509 (26.9)  │ 505 (24.0)    │ 3003 (27.5)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEFAIACT, n (%)   │ 0.0 │ 17732     │ 5600 (42.9)  │ 1106 (52.5)   │ 4489 (41.0)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 1.0 │           │ 2893 (22.2)  │ 446 (21.2)    │ 2443 (22.3)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 1651 (12.6)  │ 274 (13.0)    │ 1376 (12.6)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 2916 (22.3)  │ 281 (13.3)    │ 2631 (24.1)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│ YEOTHACT, n (%)   │ 0.0 │ 17694     │ 8200 (62.6)  │ 1411 (66.9)   │ 6780 (61.8)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 1.0 │           │ 2576 (19.7)  │ 394 (18.7)    │ 2180 (19.9)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 2.0 │           │ 1090 (8.3)   │ 182 (8.6)     │ 907 (8.3)     │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤
│                   │ 3.0 │           │ 1232 (9.4)   │ 123 (5.8)     │ 1107 (10.1)   │
├───────────────────┼─────┼───────────┼──────────────┼───────────────┼───────────────┤